; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global videoFiles
global VIDEO_FORMAT_FAILED
videoFiles := []


Gui Font, s14 cNavy, 標楷體
Gui Color, 0xB5B5B5
Gui Add, Text, x233 y144 w0 h0 +0x200, Text
Gui Add, Text, x260 y58 w120 h23 +0x200, 語音轉文字
Gui Add, Text, x45 y142 w120 h23 +0x200, 選擇檔案
Gui Add, Edit, hWndhEdtValue vEdtFiles x172 y113 w291 h114
Gui Add, Button, gExecute x203 y275 w80 h30, 開始
Gui Add, Button, gbtnClose x350 y275 w80 h32, 結束
Gui Add, Button, gBtnSelectFiles x474 y116 w118 h23, 選擇檔案

Gui Show, w620 h420, 語音轉文字
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }
Return

btnSelectFiles:
  ;FileSelectFile, OutputVar , Options, RootDir\Filename, Title, Filter
  FileSelectFile, files, M3, , %VIDEO_SELECT_TITLE%, *.wav  ; M3 = Multiselect existing files.
  if (files = "") {
    return
  }
  ;msgbox files=%files%
  folder := ""
  Loop, parse, files, `n
  {
    if (A_Index = 1) {
      folder = %A_LoopField%
    } else {
      iswav := chkVideoFile(A_LoopField)
      if (iswav = 1) {
        videoFiles.push(folder . "\" . A_LoopField)  
      }
    }
  }
  GuiControl, , EdtFiles, %files%
Return


Execute(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  Gui, Submit
  GuiControlGet, CmbLanguage,,
  iPos := InStr(CmbLanguage, " ")
  Language := Substr(CmbLanguage, 1, iPos-1)
  if (Language = "zh-TW") {
    Language := "cmn-hant-tw"
  } 
  ;MsgBox lang=%Language%$
  
  GuiControlGet, edtOutputFilename,,
;  edtOutputFilename
  
  for index, element in videoFiles
  {
    videoFilename := element
    if (index = 1) {
      newFilename := deleteOldFile(edtOutputFilename, Language)
      if (InStr(edtOutputFilename, ".txt") > 0) {
        batFilename := "001.bat"
      } else {
        batFilename := "001.bat"
      }
      ;;MsgBox %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
      Run %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
    } else {
      edtOutputFilename := videoFilename
      StringReplace edtOutputFilename, edtOutputFilename, .mp4, .srt
      StringReplace edtOutputFilename, edtOutputFilename, .wav, .srt
      StringReplace edtOutputFilename, edtOutputFilename, .mp3, .srt
      newFilename := deleteOldFile(edtOutputFilename, Language)
      if (InStr(edtOutputFilename, ".txt") > 0) {
        batFilename := "001.bat"
      } else {
        batFilename := "001.bat"
      }
      Run %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
    }
  }
  ExitApp
}  
chkVideoFile(file) {
  ;MsgBox file=%file%
  iPos := InStr(file, ".wav")
  if (iPos <= 0) {
    MsgBox %VIDEO_FORMAT_FAILED% (%file%)
    Return false
  }
  Return True
}
btnClose:
  WinClose
Return

deleteOldFile(file, language) {
  iPos := InStr(file, ".")
  newFilename := Substr(file, 1, iPos) . language . Substr(file, iPos, 10)
  if FileExist(newFilename) {
    FileDelete, %newFilename%
  }
  return newFilename
}

GuiEscape:
GuiClose:
    ExitApp
