; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

global videoFiles
global VIDEO_FORMAT_FAILED
videoFiles := []
#Include %A_ScriptDir%\read-ini.ahk

Gui +Resize
Gui Font, s12, 標楷體
Gui Color, 0xD2EDFD
Gui Font
Gui Font, s14 cRed, 標楷體
Gui Add, Text, x226 y6 w223 h23 +0x200, 將您的語音轉成文字
Gui Font
Gui Font, s12, 標楷體
Gui Add, Text, x-19 y47 w720 h2 +0x10
Gui Add, Text,  x80 y95 w91 h23 +0x200, 選擇檔案
Gui Add, Edit, hWndhEdtValue vEdtFiles x187 y67 w301 h92
Gui Add, Button, gBtnSelectFiles x498 y64 w131 h39, 選擇檔案...
Gui Add, Button, gExecute x243 y357 w80 h22, 開始
Gui Add, Button, gbtnClose x360 y357 w80 h23, 關閉
Gui Add, Text, x80 y230 w91 h23 +0x200, 輸出路徑
Gui Add, Edit, vEdtOutput x183 y220 w301 h92
Gui Add, Button, gBtnSelectOutput x497 y218 w131 h39, 選擇...


Gui Show, w675 h420, 語音轉文字
Return

GuiSize:
    If (A_EventInfo == 1) {
        Return
    }
Return

btnSelectFiles:
  ;FileSelectFile, OutputVar , Options, RootDir\Filename, Title, Filter
  FileSelectFile, files, M3, , %VIDEO_SELECT_TITLE%, *.mp4  ; M3 = Multiselect existing files.
  if (files = "") {
    return
  }
  ;msgbox files=%files%
  folder := ""
  Loop, parse, files, `n
  {
    if (A_Index = 1) {
      folder = %A_LoopField%
    } else {
      isMP4 := chkVideoFile(A_LoopField)
      if (isMP4 = 1) {
        videoFiles.push(folder . "\" . A_LoopField)  
      }
    }
  }
  GuiControl, , EdtFiles, %files%
Return

Execute(CtrlHwnd, GuiEvent, EventInfo, ErrLevel := "") {
  Gui, Submit
  GuiControlGet, CmbLanguage,,
  iPos := InStr(CmbLanguage, " ")
  Language := Substr(CmbLanguage, 1, iPos-1)
  if (Language = "zh-TW") {
    Language := "cmn-hant-tw"
  } 
  ;MsgBox lang=%Language%$
  
  GuiControlGet, edtOutputFilename,,
;  edtOutputFilename
  
  for index, element in videoFiles
  {
    videoFilename := element
    if (index = 1) {
      newFilename := deleteOldFile(edtOutputFilename, Language)
      if (InStr(edtOutputFilename, ".txt") > 0) {
        batFilename := "001.bat"
      } else {
        batFilename := "001.bat"
      }
      ;;MsgBox %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
      Run %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
    } else {
      edtOutputFilename := videoFilename
      StringReplace edtOutputFilename, edtOutputFilename, .mp4, .srt
      StringReplace edtOutputFilename, edtOutputFilename, .wav, .srt
      StringReplace edtOutputFilename, edtOutputFilename, .mp3, .srt
      newFilename := deleteOldFile(edtOutputFilename, Language)
      if (InStr(edtOutputFilename, ".txt") > 0) {
        batFilename := "001.bat"
      } else {
        batFilename := "001.bat"
      }
      Run %A_ScriptDir%\%batFilename% %Language% "%videoFilename%" "%edtOutputFilename%" "%newFilename%"
    }
  }
  ExitApp
}  

GuiDropFiles(GuiHwnd, FileArray, CtrlHwnd, X, Y) {
  videoFiles := []
  for i, file in FileArray 
  { 
    ;MsgBox File %i% is:`n%file%
    if (chkVideoFile(file)) {
      videoFiles.push(file)
    }
  }
  for index, element in videoFiles ; Enumeration is the recommended approach in most cases.
  {
    if (index = 1) {
      name := element
      StringReplace name, name, .mp4, .srt
      StringReplace name, name, .mp3, .srt
      StringReplace name, name, .wav, .srt
      GuiControl, , edtOutputFilename, %name%
    }
    files := files . element . "|"
  }
  GuiControl, , ListBox1, %files%  
}

chkVideoFile(file) {
  ;MsgBox file=%file%
  iPos := InStr(file, ".wav")
  if (iPos <= 0) {
    MsgBox %VIDEO_FORMAT_FAILED% (%file%)
    Return false
  }
  Return True
}



BtnSelectOutput:
  FileSelectFolder, folder, *C:\Users\%A_UserName%\Documents, 3, 選擇輸出資料夾
  if (folder = "") {
    ;MsgBox, The user pressed cancel.
    return
  }
  GuiControl,, EdtOutput, %folder%
  Return
  
btnClose:
  WinClose
Return

EdtFiles:
  Return


deleteOldFile(file, language) {
  iPos := InStr(file, ".")
  newFilename := Substr(file, 1, iPos) . language . Substr(file, iPos, 10)
  if FileExist(newFilename) {
    FileDelete, %newFilename%
  }
  return newFilename
}



GuiEscape:
GuiClose:
    ExitApp
